# Exclusions
Lint/DebugCalls:
  Excluded:
    - src/tanda_cli/debug.cr

# Disabled by default
Layout/LineLength:
  Enabled: true
  MaxLength: 180 # default

Lint/ComparisonToBoolean:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/LargeNumbers:
  Enabled: true
  IntMinDigits: 5 # i.e. integers higher than 9999

Style/PredicateName:
  Enabled: true

Lint/UselessAssign:
  Enabled: true
  ExcludeTypeDeclarations: true

Lint/SpecFilename:
  Enabled: true
  Excluded:
    - spec/core_ext/spec_mock_hack.cr

Lint/NotNil:
  Enabled: true
  Excluded:
    - spec/**/*

### DISABLED ###

Documentation/DocumentationAdmonition:
  Enabled: false

