name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      crystal_version:
        description: "Crystal version"
        required: false
        default: "1.11.0"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: ["${{ inputs.crystal_version }}", nightly]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Install shards
        run: shards install --frozen
        if: matrix.crystal == inputs.crystal_version

      # If development shards break on nightly that's okay, we mostly only care about our app code
      - name: Install shards without development
        run: shards install --production
        if: matrix.crystal == 'nightly'

      - name: Check for dead code
        run: crystal tool unreachable src/tanda_cli.cr --check
        if: matrix.crystal == inputs.crystal_version

      - name: Check formatting
        run: crystal tool format; git diff --exit-code
        if: matrix.crystal == inputs.crystal_version

      - name: Lint
        run: ./bin/ameba
        if: matrix.crystal == inputs.crystal_version

      - name: Compile
        run: crystal build src/tanda_cli.cr

      - name: Run tests
        run: ./scripts/run-spec.sh
        if: matrix.crystal == inputs.crystal_version

