name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run Lint
      run: ./bin/ameba
    - name: Compile
      run: crystal build src/tanda_cli.cr
    # TODO: Add Tests
    # - name: Run tests
    #   run: crystal spec --order=random --error-on-warnings
