name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.5.0

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Lint
      run: ./bin/ameba
    - name: Compile
      run: crystal build src/tanda_cli.cr
    - name: Run tests
      run: ./scripts/run-spec.sh
