name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      crystal_version:
        description: "Crystal version"
        required: false
        default: "1.13.3"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: ["${{ inputs.crystal_version }}"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Install shards
        run: shards install --frozen

      - name: Check for dead code
        run: crystal tool unreachable src/tanda_cli.cr --check

      - name: Check formatting
        run: crystal tool format; git diff --exit-code

      - name: Lint
        run: ./bin/ameba

      - name: Compile
        run: crystal build src/tanda_cli.cr

      - name: Run tests
        run: ./scripts/run-spec.sh

